# Question 1 `GYM members`

In [12]:
"""GYM members manager system"""

# imports
import numpy as np

# gym data nd array
gym_data = np.array(
    [
        # zero values == Null
        # column 0 == age
        # column 1 == weight
        # column 2 == height
        # column 3 == Number of sessions per week
        [28, 75, 175, 4],
        [34, 68, 168, 3],
        [45, 82, 180, 2],
        [22, 58, 162, 5],
        [38, 90, 0, 1],
        [29, 65, 170, 0],
    ],
    dtype=float,
)
print(f"Before preprocessing:\n{gym_data}")
# members name
members_name = np.array(["Ali", "Sara", "Reza", "Neda", "Hassan", "Maryam"])

# preprocessing
columns_mean = np.mean(gym_data, axis=0)
# condition = where cells are zero
# np.take = replace column mean  with zero cell index
# np.where return row and col and [1] tell only return column
gym_data[gym_data == 0] = np.take(columns_mean, np.where(gym_data == 0)[1])
print(f"\nafter preprocessing:\n{gym_data}")

# fitness array weight , height , sessions per week featurs
fitness_arr = gym_data[:, 1:4]
# height **2 >> meter | weight >> kilogram
bmi_score = fitness_arr[:, 0] / ((fitness_arr[:, 1] * 0.01) ** 2)
# fitness score a new feature in fitness array == (bmi score* w1)*(sessions * w2)
weights = np.array([0.7, 0.3])
fitness_score = ((bmi_score * weights[0]) + (fitness_arr[:, -1] * weights[1])).reshape(
    -1, 1
)
# stacking arrays
fitness_arr = np.hstack((fitness_arr, fitness_score))
# fitness array with a new feature
print(f"\nfitness table:\n{fitness_arr}")
# Who is the fittest guy in the gym ?
fittest_index = fitness_arr[:, -1].argmax()
print(f"\nfittest member :{members_name[fittest_index]}\
          with score: {fitness_arr[:,-1].max():.2f}")

# use std to find the record that has the most different session per week
# to detect anomaly in sessions we should measure distance
#  from mean and we can devide it by std == Z score
# bigger Z score == more distance
fit_std = fitness_arr[:, 2].std()
fit_mean = fitness_arr[:, 2].mean()
z_score = np.abs((fitness_arr[:, 2] - fit_mean) / fit_std)
anomaly_index = z_score.argmax()
anomaly_person = members_name[anomaly_index]
print(f"\nanomaly person in session col is {anomaly_person},\
      {fitness_arr[anomaly_index,2]} session per week")

Before preprocessing:
[[ 28.  75. 175.   4.]
 [ 34.  68. 168.   3.]
 [ 45.  82. 180.   2.]
 [ 22.  58. 162.   5.]
 [ 38.  90.   0.   1.]
 [ 29.  65. 170.   0.]]

after preprocessing:
[[ 28.   75.  175.    4. ]
 [ 34.   68.  168.    3. ]
 [ 45.   82.  180.    2. ]
 [ 22.   58.  162.    5. ]
 [ 38.   90.  142.5   1. ]
 [ 29.   65.  170.    2.5]]

fitness table:
[[ 75.         175.           4.          18.34285714]
 [ 68.         168.           3.          17.76507937]
 [ 82.         180.           2.          18.31604938]
 [ 58.         162.           5.          16.97020271]
 [ 90.         142.5          1.          31.32493075]
 [ 65.         170.           2.5         16.49394464]]

fittest member :Hassan          with score: 31.32

anomaly person in session col is Neda,      5.0 session per week


# Question 2 `Food offer`

In [ ]:
# This cell will Sugest food to customers by their taste

# imports
import numpy as np

# variables
recipes = np.array(
    [
        # first column =  Cooking time
        # second column = Calories
        # third column = spiciness
        # forth column = nb of ingredients
        [15, 350, 2, 5],
        [45, 600, 7, 10],
        [10, 200, 0, 3],
        [30, 450, 5, 7],
        [60, 800, 8, 12],
    ]
)
# Food's names
recipe_names = np.array(["Salad", "Curry", "Toast", "Pasta", "Stew"])

# shape and view of data
print(f"shape of recipes array:\n{recipes.shape}\nview of recipes array:\n{recipes}")

# preprocessing | Min Max scaling
min_arr = np.min(recipes, axis=0)
max_arr = np.max(recipes, axis=0)
scaled_recipes = (recipes - min_arr) / (max_arr - min_arr)

print(f"\nrecipe array scaled:\n{scaled_recipes}")

# test data
users = np.array([[10, 250, 1, 4], [50, 700, 8, 11], [25, 400, 4, 6]])
# scale user with recipes array min and max
scaled_customer = (users - min_arr) / (max_arr - min_arr)
print(f"\ncustomer array scaled:\n{scaled_customer}")
# scaled_customer.reshape(3,1,4) = 3,1,4 that means our 1 dim
# in each dim has one person and four features that will be compared to 5 food with 4 features
# in the other hand numpy said 1 in N is ok , so we have 3 of 1 in N
# So each row has a 1×4 matrix that is OK to broadcasting
users_taste = np.linalg.norm(scaled_customer.reshape(3, 1, 4) - scaled_recipes, axis=2)
# find favorit food
taste_index = users_taste.argmin(axis=1)
user_sorted_taste = users_taste.argsort(axis=1)
print(f"favorit foods by order : {recipe_names[taste_index]}")
print(
    f"\nfavorit foods by order (first food = nearest food): \n{recipe_names[user_sorted_taste]}"
)

shape of recipes array:
(5, 4)
view of recipes array:
[[ 15 350   2   5]
 [ 45 600   7  10]
 [ 10 200   0   3]
 [ 30 450   5   7]
 [ 60 800   8  12]]

recipe array scaled:
[[0.1        0.25       0.25       0.22222222]
 [0.7        0.66666667 0.875      0.77777778]
 [0.         0.         0.         0.        ]
 [0.4        0.41666667 0.625      0.44444444]
 [1.         1.         1.         1.        ]]

customer array scaled:
[[0.         0.08333333 0.125      0.11111111]
 [0.8        0.83333333 1.         0.88888889]
 [0.3        0.33333333 0.5        0.33333333]]
favorit foods by order : ['Toast' 'Curry' 'Pasta']

favorit foods by order (first food = nearest food): 
[['Toast' 'Salad' 'Pasta' 'Curry' 'Stew']
 ['Curry' 'Stew' 'Pasta' 'Salad' 'Toast']
 ['Pasta' 'Salad' 'Toast' 'Curry' 'Stew']]


# Question 3 `High School`

In [ ]:
# This program is a high school grading management system

# imports
import numpy as np

# variables
scores = np.array(
    [
        # first feature = Quiz
        # second feature = Midterm
        # third feature = Final exam
        [18, 15, 20],
        [12, 14, 16],
        [20, 19, 18],
        [10, 8, 15],
    ]
)

print(f"scores shape:\n{scores.shape}")
# weight schemes
weight_schemes = np.array(
    [
        # scheme A | Quiz = most important
        [0.5, 0.3, 0.2],
        # scheme B | final = most important
        [0.2, 0.3, 0.5],
        # scheme C | final = very very important!
        [0.1, 0.2, 0.7],
    ]
)

print(f"weight schemes shape:\n{weight_schemes.shape}")
# final score each row has student score with A,B,C schemes.
final_scores = scores @ weight_schemes.T
print(f"each row is a student each column is a weight scheme:\n{final_scores}\n\
final score array shape = {final_scores.shape}\n")

# whitch scheme for each student has most score
scheme_map = np.array(["A", "B", "C"])
max_score_each = final_scores.argmax(axis=1)
best_scheme_each = scheme_map[max_score_each]
for i, scheme in enumerate(best_scheme_each, start=1):
    print(f"student {i},best scheme is {scheme}")

# best scheme for all classes
mean_score_all = final_scores.mean(axis=0)
max_score_all = mean_score_all.argmax()

print(f"{scheme_map[max_score_all]} is better for all students:\n\
{final_scores[:,max_score_all]} are students \
final score with scheme {scheme_map[max_score_all]}")
print("#-#" * 10)
# scheme D is new scheme [0.2, 0.4 , 0.4]
weight_schemes_n = np.array(
    [
        # scheme A | Quiz = most important
        [0.5, 0.3, 0.2],
        # scheme B | final = most important
        [0.2, 0.3, 0.5],
        # scheme C | final = very very important!
        [0.1, 0.2, 0.7],
        # scheme D | final = Quiz × 2
        [0.2, 0.4, 0.4],
    ]
)

print(f"weight schemes shape:\n{weight_schemes_n.shape}")
# final score each row has student score with A,B,C,D schemes.
final_scores_n = scores @ weight_schemes_n.T
print(f"each row is a student each column is a weight scheme:\n{final_scores_n}\n\
final score array shape = {final_scores_n.shape}\n")

scheme_map_n = np.array(["A", "B", "C", "D"])

# whitch scheme for each student has most score
max_score_each_n = final_scores_n.argmax(axis=1)
best_scheme_each_n = scheme_map_n[max_score_each_n]
for i, scheme in enumerate(best_scheme_each_n, start=1):
    print(f"student {i},best scheme is {scheme}")

# best scheme for all classes
mean_score_all_n = final_scores_n.mean(axis=0)
max_score_all_n = mean_score_all_n.argmax()

print(f"{scheme_map_n[max_score_all_n]} is better for all students:\n\
{final_scores_n[:,max_score_all_n]} are students \
final score with scheme {scheme_map_n[max_score_all_n]}")

scores shape:
(4, 3)
weight schemes shape:
(3, 3)
each row is a student each column is a weight scheme:
[[17.5 18.1 18.8]
 [13.4 14.6 15.2]
 [19.3 18.7 18.4]
 [10.4 11.9 13.1]]
final score array shape = (4, 3)

student 1,best scheme is C
student 2,best scheme is C
student 3,best scheme is A
student 4,best scheme is C
C is better for all students:
[18.8 15.2 18.4 13.1] are students final score with scheme C
#-##-##-##-##-##-##-##-##-##-#
weight schemes shape:
(4, 3)
each row is a student each column is a weight scheme:
[[17.5 18.1 18.8 17.6]
 [13.4 14.6 15.2 14.4]
 [19.3 18.7 18.4 18.8]
 [10.4 11.9 13.1 11.2]]
final score array shape = (4, 4)

student 1,best scheme is C
student 2,best scheme is C
student 3,best scheme is A
student 4,best scheme is C
C is better for all students:
[18.8 15.2 18.4 13.1] are students final score with scheme C


# Question 4 `Debug Weather Data`

In [9]:
# some reshape and matrix training with weather datas
# imports
import numpy as np


# function
def analyze_day(weather_data):
    print(f"data shape:\n{weather_data.shape}\n{"--"*30}")


# variables
weather_data = np.random.randn(2, 8, 4) * 5 + 20

# day 2 reshape
day_2 = weather_data[1]
analyze_day(day_2.T)

# flatten weather data
f_weather_data = weather_data.reshape(-1)
print(f"shape of flatten weather data:\n{f_weather_data.shape}\n{"--"*30}")

# different between flatten and Transpose an array
test_arr = np.array([[1, 2], [3, 4]])

print(f"This is test array:\n{test_arr}\
\nThis is the shape before do anything:\
\n{test_arr.shape}\nthis is the array after flatten:\n{test_arr.reshape(-1)}\n\
and this is shape of flatten:\n {test_arr.reshape(-1).shape}\
\nthis is the array after transpose:\n{test_arr.T}\n\
this is the shape after transpose:\n{test_arr.T.shape}")

# add Day 3 to the weather data array with stacking
day3 = np.random.randn(8, 4).reshape(1, 8, 4)
weather_data = np.vstack((weather_data, day3))
print(f"shape of weather data after concat day 3:\n{weather_data.shape}")

data shape:
(4, 8)
------------------------------------------------------------
shape of flatten weather data:
(64,)
------------------------------------------------------------
This is test array:
[[1 2]
 [3 4]]
This is the shape before do anything:
(2, 2)
this is the array after flatten:
[1 2 3 4]
and this is shape of flatten:
 (4,)
this is the array after transpose:
[[1 3]
 [2 4]]
this is the shape after transpose:
(2, 2)
shape of weather data after concat day 3:
(3, 8, 4)


# Question 5 `Smart TODO list`

In [29]:
# imports numpy
import numpy as np


# functions
def importance_func(arr):
    print(arr.shape)


# variables
importance = np.array([3, 8, 1, 9, 4, 7])
importance_reshape = importance.reshape(6, -1)
importance_expand = np.expand_dims(importance, axis=1)
# call function with reshape variable
importance_func(importance_reshape)
# call function with expand variable
importance_func(importance_expand)
# model out
model_out = np.array([[[0.9]]])
print(f"model out shape:\n{model_out.shape}")
print(f"extract value with np.squeeze(model_out):\n{np.squeeze(model_out)}")
print(f"extract with indexing model_out[0,0,0]:\n{model_out[0,0,0]}")
print(f"extrat with .item():\n{model_out.item()}")
# shalow copy effect  notes[5,10,15,20,25] => notes[5,999,15,20,25]
notes = np.array([5, 10, 15, 20, 25])
pinned = notes[1:3]
pinned[0] = 999
print(f"shalow copy:\n{notes}")

# deep1copy effect  notes[5,10,15,20,25] => notes[5,999,15,20,25]
notes = np.array([5, 10, 15, 20, 25])
pinned = notes[1:3].copy()
pinned[0] = 999
print(f"deep copy:\n{notes}")

(6, 1)
(6, 1)
model out shape:
(1, 1, 1)
extract value with np.squeeze(model_out):
0.9
extract with indexing model_out[0,0,0]:
0.9
extrat with .item():
0.9
shalow copy:
[  5 999  15  20  25]
deep copy:
[ 5 10 15 20 25]


# Question 6 `Marathon`

In [ ]:
# imports
import numpy as np

# variables
bib_numbers = np.array([101, 102, 103, 104, 105, 106])
times_5k = np.array([22.3, 25.1, 21.8, 26.4, 23.0, 24.7])
print(f"{"-"*30}\nbib numbers before stacking:\n{bib_numbers}")
print(f"times 5k before stacking:\n{times_5k}")

# new runners
bib_numbers_2 = np.array([107, 108])
times_5k_2 = np.array([20.5, 27.9])
bib_numbers = np.hstack((bib_numbers, bib_numbers_2))
times_5k = np.hstack((times_5k, times_5k_2))
print(f"{"-"*30}\nbib numbers after stacking:\n{bib_numbers}")
print(f"times 5k after stacking:\n{times_5k}")

# shuffle runners
shuffeld_index = np.random.permutation(bib_numbers.size)
shuffeld_bib = bib_numbers[shuffeld_index]
shuffeld_times = times_5k[shuffeld_index]

print(f"{"-"*30}\nbib numbers after shuffeling:\n{shuffeld_bib}")
print(f"times 5k after shuffeling:\n{shuffeld_times}\n")
# sort array by time
sort_index = shuffeld_times.argsort()
a_z_bib = shuffeld_bib[sort_index]
a_z_times = shuffeld_times[sort_index]

for i, (runner, time) in enumerate(zip(a_z_bib, a_z_times), start=1):
    print(f"{"-"*30}\n{i}.bib runner: {runner} time: {time}\n")


unhappy_runner_index = np.where(a_z_bib == 104)[0].item()
print(f"{"-"*30}\nrunner with bib {104} at {unhappy_runner_index+1} \
place with time: {a_z_times[unhappy_runner_index]} ")

------------------------------
bib numbers before stacking:
[101 102 103 104 105 106]
times 5k before stacking:
[22.3 25.1 21.8 26.4 23.  24.7]
------------------------------
bib numbers after stacking:
[101 102 103 104 105 106 107 108]
times 5k after stacking:
[22.3 25.1 21.8 26.4 23.  24.7 20.5 27.9]
------------------------------
bib numbers after shuffeling:
[102 101 106 103 105 104 107 108]
times 5k after shuffeling:
[25.1 22.3 24.7 21.8 23.  26.4 20.5 27.9]

------------------------------
1.bib runner: 107 time: 20.5

------------------------------
2.bib runner: 103 time: 21.8

------------------------------
3.bib runner: 101 time: 22.3

------------------------------
4.bib runner: 105 time: 23.0

------------------------------
5.bib runner: 106 time: 24.7

------------------------------
6.bib runner: 102 time: 25.1

------------------------------
7.bib runner: 104 time: 26.4

------------------------------
8.bib runner: 108 time: 27.9

------------------------------
runner with 

# Question 7 `Neuron`

In [87]:
#imports 
import numpy as np
#variables
X_messages = np.array(
    [
      [12, 0, 1],
      [45, 5, 8],
      [8, 0, 0],
      [30, 3, 4]
    ]
)
w = np.array([0.1, 0.8, 0.5])
w_n = np.array([0.1, 0.8, 0.1])
b = -2.0
#raw output
model_output = X_messages @ w + b
print(f"raw model output:\n{model_output}")
#apply reLU
model_output = np.where(model_output < 0 ,0,model_output)
print(f"use reLU to remove negative values: \n{model_output}")

#threshold At 0.5 | Atention : reLU output is not probability and it's not between 0 to 1 , it's just a random threshold
threshold = 0.5
predict = np.where(model_output < threshold,0,1)
print(f"Model prediction:\n{predict}")

raw model output:
[-0.3 10.5 -1.2  5.4]
use reLU to remove negative values: 
[ 0.  10.5  0.   5.4]
Model prediction:
[0 1 0 1]
