# Question 1 `GYM members`

In [ ]:
"""GYM members manager system"""

# imports
import numpy as np

# gym data nd array
gym_data = np.array(
    [
        # zero values == Null
        # column 0 == age
        # column 1 == weight
        # column 2 == height
        # column 3 == Number of sessions per week
        [28, 75, 175, 4],
        [34, 68, 168, 3],
        [45, 82, 180, 2],
        [22, 58, 162, 5],
        [38, 90, 0, 1],
        [29, 65, 170, 0],
    ],
    dtype=float,
)
print(f"Before preprocessing:\n{gym_data}")
# members name
members_name = np.array(["Ali", "Sara", "Reza", "Neda", "Hassan", "Maryam"])

# preprocessing
columns_mean = np.mean(gym_data, axis=0)
# condition = where cells are zero
# np.take = replace column mean  with zero cell index
# np.where return row and col and [1] tell only return column
gym_data[gym_data == 0] = np.take(columns_mean, np.where(gym_data == 0)[1])
print(f"\nafter preprocessing:\n{gym_data}")

# fitness array weight , height , sessions per week featurs
fitness_arr = gym_data[:, 1:4]
# height **2 >> meter | weight >> kilogram
bmi_score = fitness_arr[:, 0] / ((fitness_arr[:, 1] * 0.01) ** 2)
# fitness score a new feature in fitness array == (bmi score* w1)*(sessions * w2)
weights = np.array([1, 1])
fitness_score = ((bmi_score * weights[0]) + (fitness_arr[:, -1] * weights[1])).reshape(
    -1, 1
)
# stacking arrays
fitness_arr = np.hstack((fitness_arr, fitness_score))
# fitness array with a new feature
print(f"\nfitness table:\n{fitness_arr}")
# Who is the fittest guy in the gym ?
fittest_index = fitness_arr[:, -1].argmax()
print(
    f"\nfittest member :{members_name[fittest_index]}\
          with score: {fitness_arr[:,-1].max():.2f}"
)

# use std to find the record that has the most different session per week
# to detect anomaly in sessions we should measure distance
#  from mean and we can devide it by std == Z score
# bigger Z score == more distance
fit_std = fitness_arr[:, 2].std()
fit_mean = fitness_arr[:, 2].mean()
z_score = np.abs((fitness_arr[:, 2] - fit_mean) / fit_std)
anomaly_index = z_score.argmax()
anomaly_person = members_name[anomaly_index]
print(
    f"\nanomaly person in session col is {anomaly_person},\
      {fitness_arr[anomaly_index,2]} session per week"
)

Before preprocessing:
[[ 28.  75. 175.   4.]
 [ 34.  68. 168.   3.]
 [ 45.  82. 180.   2.]
 [ 22.  58. 162.   5.]
 [ 38.  90.   0.   1.]
 [ 29.  65. 170.   0.]]

after preprocessing:
[[ 28.   75.  175.    4. ]
 [ 34.   68.  168.    3. ]
 [ 45.   82.  180.    2. ]
 [ 22.   58.  162.    5. ]
 [ 38.   90.  142.5   1. ]
 [ 29.   65.  170.    2.5]]

fitness table:
[[ 75.         175.           4.          28.48979592]
 [ 68.         168.           3.          27.09297052]
 [ 82.         180.           2.          27.30864198]
 [ 58.         162.           5.          27.10028959]
 [ 90.         142.5          1.          45.32132964]
 [ 65.         170.           2.5         24.99134948]]

fittest member :Hassan with score: 45.32

anomaly person in session col is Neda, 5.0 session per week
