# Question 1 `GYM members`

In [ ]:
"""GYM members manager system"""

# imports
import numpy as np

# gym data nd array
gym_data = np.array(
    [
        # zero values == Null
        # column 0 == age
        # column 1 == weight
        # column 2 == height
        # column 3 == Number of sessions per week
        [28, 75, 175, 4],
        [34, 68, 168, 3],
        [45, 82, 180, 2],
        [22, 58, 162, 5],
        [38, 90, 0, 1],
        [29, 65, 170, 0],
    ],
    dtype=float,
)
print(f"Before preprocessing:\n{gym_data}")
# members name
members_name = np.array(["Ali", "Sara", "Reza", "Neda", "Hassan", "Maryam"])

# preprocessing
columns_mean = np.mean(gym_data, axis=0)
# condition = where cells are zero
# np.take = replace column mean  with zero cell index
# np.where return row and col and [1] tell only return column
gym_data[gym_data == 0] = np.take(columns_mean, np.where(gym_data == 0)[1])
print(f"\nafter preprocessing:\n{gym_data}")

# fitness array weight , height , sessions per week featurs
fitness_arr = gym_data[:, 1:4]
# height **2 >> meter | weight >> kilogram
bmi_score = fitness_arr[:, 0] / ((fitness_arr[:, 1] * 0.01) ** 2)
# fitness score a new feature in fitness array == (bmi score* w1)*(sessions * w2)
weights = np.array([1, 1])
fitness_score = ((bmi_score * weights[0]) + (fitness_arr[:, -1] * weights[1])).reshape(
    -1, 1
)
# stacking arrays
fitness_arr = np.hstack((fitness_arr, fitness_score))
# fitness array with a new feature
print(f"\nfitness table:\n{fitness_arr}")
# Who is the fittest guy in the gym ?
fittest_index = fitness_arr[:, -1].argmax()
print(f"\nfittest member :{members_name[fittest_index]}\
          with score: {fitness_arr[:,-1].max():.2f}")

# use std to find the record that has the most different session per week
# to detect anomaly in sessions we should measure distance
#  from mean and we can devide it by std == Z score
# bigger Z score == more distance
fit_std = fitness_arr[:, 2].std()
fit_mean = fitness_arr[:, 2].mean()
z_score = np.abs((fitness_arr[:, 2] - fit_mean) / fit_std)
anomaly_index = z_score.argmax()
anomaly_person = members_name[anomaly_index]
print(f"\nanomaly person in session col is {anomaly_person},\
      {fitness_arr[anomaly_index,2]} session per week")

Before preprocessing:
[[ 28.  75. 175.   4.]
 [ 34.  68. 168.   3.]
 [ 45.  82. 180.   2.]
 [ 22.  58. 162.   5.]
 [ 38.  90.   0.   1.]
 [ 29.  65. 170.   0.]]

after preprocessing:
[[ 28.   75.  175.    4. ]
 [ 34.   68.  168.    3. ]
 [ 45.   82.  180.    2. ]
 [ 22.   58.  162.    5. ]
 [ 38.   90.  142.5   1. ]
 [ 29.   65.  170.    2.5]]

fitness table:
[[ 75.         175.           4.          28.48979592]
 [ 68.         168.           3.          27.09297052]
 [ 82.         180.           2.          27.30864198]
 [ 58.         162.           5.          27.10028959]
 [ 90.         142.5          1.          45.32132964]
 [ 65.         170.           2.5         24.99134948]]

fittest member :Hassan with score: 45.32

anomaly person in session col is Neda, 5.0 session per week


# Question 2 `Food offer`

In [36]:
'''This cell will Sugest food to customers by their taste'''
# imports
import numpy as np

# variables
recipes = np.array(
    [
        # first column =  Cooking time
        # second column = Calories
        # third column = spiciness
        # forth column = nb of ingredients
        [15, 350, 2, 5],
        [45, 600, 7, 10],
        [10, 200, 0, 3],
        [30, 450, 5, 7],
        [60, 800, 8, 12],
    ]
)
# Food's names
recipe_names = np.array(["Salad", "Curry", "Toast", "Pasta", "Stew"])

# shape and view of data
print(f"shape of recipes array:\n{recipes.shape}\nview of recipes array:\n{recipes}")

# preprocessing | Min Max scaling
min_arr = np.min(recipes, axis=0)
max_arr = np.max(recipes, axis=0)
scaled_recipes = (recipes - min_arr) / (max_arr - min_arr)

print(f"\nrecipe array scaled:\n{scaled_recipes}")

# test data
users = np.array([[10, 250, 1, 4], [50, 700, 8, 11], [25, 400, 4, 6]])
# scale user with recipes array min and max
scaled_customer = (users - min_arr) / (max_arr - min_arr)
print(f"\ncustomer array scaled:\n{scaled_customer}")
# scaled_customer.reshape(3,1,4) = 3,1,4 that means our 1 dim
# in each dim has one person and four features that will be compared to 5 food with 4 features
# in the other hand numpy said 1 in N is ok , so we have 3 of 1 in N
# So each row has a 1×4 matrix that is OK to broadcasting
users_taste = np.linalg.norm(scaled_customer.reshape(3, 1, 4) - scaled_recipes, axis=2)
# find favorit food
taste_index = users_taste.argmin(axis=1)
user_sorted_taste = users_taste.argsort(axis=1)
print(f"favorit foods by order : {recipe_names[taste_index]}")
print(
    f"\nfavorit foods by order (first food = nearest food): \n{recipe_names[user_sorted_taste]}"
)

shape of recipes array:
(5, 4)
view of recipes array:
[[ 15 350   2   5]
 [ 45 600   7  10]
 [ 10 200   0   3]
 [ 30 450   5   7]
 [ 60 800   8  12]]

recipe array scaled:
[[0.1        0.25       0.25       0.22222222]
 [0.7        0.66666667 0.875      0.77777778]
 [0.         0.         0.         0.        ]
 [0.4        0.41666667 0.625      0.44444444]
 [1.         1.         1.         1.        ]]

customer array scaled:
[[0.         0.08333333 0.125      0.11111111]
 [0.8        0.83333333 1.         0.88888889]
 [0.3        0.33333333 0.5        0.33333333]]
favorit foods by order : ['Toast' 'Curry' 'Pasta']

favorit foods by order (first food = nearest food): 
[['Toast' 'Salad' 'Pasta' 'Curry' 'Stew']
 ['Curry' 'Stew' 'Pasta' 'Salad' 'Toast']
 ['Pasta' 'Salad' 'Toast' 'Curry' 'Stew']]
