# Question 1

In [1]:
import numpy as np

song = np.array([0.7, 0.9, 0.6])
user_taste = np.array([0.6, 0.8, 0.5])

elementwise = song * user_taste

print(elementwise)
print(np.dot(song, user_taste))

w = np.array([0.6, 0.8, 0.5])
b = 0.3

print(np.dot(song, w) + b)

song1 = np.array([0.9, 0.1])
song2 = np.array([0.85, 0.15])
song3 = np.array([-0.9, -0.1])


def cosine_similarity(x, y):
    return np.dot(x, y) / (np.linalg.norm(x) * np.linalg.norm(y))


cosine_similarity_song1_song2 = cosine_similarity(song1, song2)
cosine_similarity_song1_song3 = cosine_similarity(song1, song3)
cosine_similarity_song2_song3 = cosine_similarity(song2, song3)

print(f"cosine_similarity_song1_song2: {cosine_similarity_song1_song2}")
print(f"cosine_similarity_song1_song3: {cosine_similarity_song1_song3}")
print(f"cosine_similarity_song2_song3: {cosine_similarity_song2_song3}")

songs = np.random.rand(5, 3)

# songs = [[-0.52019337, 0.02765299, 0.45786853],
#          [0.54900505, 0.17461988, 0.40596692],
#          [0.93361316, 0.72608967, 0.07674054],
#          [0.21292646, 0.72053582, 0.4500854 ],
#          [0.98442785, 0.46167515, 0.2692847 ],]

# print(songs)

print(
    np.dot(songs, user_taste)
    / (np.linalg.norm(songs, axis=1) * np.linalg.norm(user_taste))
)

[0.42 0.72 0.3 ]
1.4400000000000002
1.7400000000000002
cosine_similarity_song1_song2: 0.9979517409161514
cosine_similarity_song1_song3: -0.9999999999999999
cosine_similarity_song2_song3: -0.9979517409161514
[0.8699115  0.94040498 0.99160501 0.9984236  0.82046044]


# Question 2

In [2]:
import numpy as np

stats = np.random.rand(4, 3)

skill_matrix = np.random.rand(3, 5)

super_hero = stats @ skill_matrix

print(
    f" super hero matrix:\n{super_hero}\nskill matrix : \n{skill_matrix}\nstats matrix:\n{stats}"
)

X_chars = np.array([[80, 40, 60], [30, 90, 50], [70, 70, 70], [95, 20, 40]])

W_skills = np.random.randn(3, 3)

W_wrong = np.random.randn(5, 3)

b_skills = np.array([1.0, -0.5, 0.2])

Z = X_chars @ W_skills + b_skills

Z_wrong = X_chars @ W_wrong.T

print(f"neoruns predicts: \n{Z_wrong.shape}")

 super hero matrix:
[[0.46252028 0.99317608 0.74605583 0.41809573 0.5576944 ]
 [0.53289426 0.63604514 0.59705991 0.51868843 0.48422155]
 [1.07661706 1.40333807 1.27283133 0.71725045 0.7266907 ]
 [1.41343146 0.86101497 1.16184683 1.14933175 0.7703955 ]]
skill matrix : 
[[0.25620052 0.8980232  0.59235188 0.24086583 0.44826555]
 [0.81958302 0.56471791 0.71112542 0.44854092 0.27620695]
 [0.63335064 0.2392418  0.44165161 0.71775746 0.47159011]]
stats matrix:
[[0.98342874 0.11952921 0.17778654]
 [0.50257498 0.1256758  0.47545943]
 [0.94137967 0.95003075 0.08969129]
 [0.11193426 0.93058379 0.98217817]]
neoruns predicts: 
(4, 5)


## Q3

In [3]:
# Q3
import numpy as np

np.random.seed(0)
questions = np.array(["Q1", "Q2", "Q3", "Q4", "Q5"])
answers = np.array(["B", "D", "A", "C", "B"])
shuffle_indexes = np.random.permutation(len(questions))
questions_shuffled = questions[shuffle_indexes]
answers_shuffled = answers[shuffle_indexes]
print(questions_shuffled)
print(answers_shuffled)

new_questions = np.array(["Q6", "Q7"])
new_answers = np.array(["A", "D"])

stacked_question = np.hstack((questions_shuffled, new_questions))

stacked_answers = np.hstack((answers_shuffled, new_answers))

print(f"stacked_question: {stacked_question}")
print(f"stacked_answers: {stacked_answers}")

difficulty = np.array([1, 2, 1, 3, 2, 2, 3])

result = np.vstack((stacked_question, stacked_answers, difficulty)).T
print(f"result: {result}")
print(f"result shape: {result.shape}")

['Q3' 'Q1' 'Q2' 'Q4' 'Q5']
['A' 'B' 'D' 'C' 'B']
stacked_question: ['Q3' 'Q1' 'Q2' 'Q4' 'Q5' 'Q6' 'Q7']
stacked_answers: ['A' 'B' 'D' 'C' 'B' 'A' 'D']
result: [['Q3' 'A' '1']
 ['Q1' 'B' '2']
 ['Q2' 'D' '1']
 ['Q4' 'C' '3']
 ['Q5' 'B' '2']
 ['Q6' 'A' '2']
 ['Q7' 'D' '3']]
result shape: (7, 3)


# Question 4

In [4]:
# Q4
import numpy as np

camera_frames = np.random.rand(6, 9)
# print(camera_frames)

camera_frames_flatten = camera_frames.reshape(6, -1)
print(f"camera_frames_flatten:\n {camera_frames_flatten}")


log = np.random.rand(6, 4)
new_log = log.T

print(f"new_log shape:{new_log.shape}")

week_temps = np.arange(84).reshape(7, 4, 3)
print(f"week_temps:{week_temps.shape}")

week_temps_transpose = week_temps.T
print(f"week_temps_transpose: {week_temps_transpose.shape}")

camera_frames_flatten:
 [[0.60276338 0.54488318 0.4236548  0.64589411 0.43758721 0.891773
  0.96366276 0.38344152 0.79172504]
 [0.52889492 0.56804456 0.92559664 0.07103606 0.0871293  0.0202184
  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443 0.63992102
  0.14335329 0.94466892 0.52184832]
 [0.41466194 0.26455561 0.77423369 0.45615033 0.56843395 0.0187898
  0.6176355  0.61209572 0.616934  ]
 [0.94374808 0.6818203  0.3595079  0.43703195 0.6976312  0.06022547
  0.66676672 0.67063787 0.21038256]
 [0.1289263  0.31542835 0.36371077 0.57019677 0.43860151 0.98837384
  0.10204481 0.20887676 0.16130952]]
new_log shape:(4, 6)
week_temps:(7, 4, 3)
week_temps_transpose: (3, 4, 7)


# Question 5

In [5]:
# Q5
import numpy as np

confidence = np.array([0.9, 0.4, 0.7, 0.95, 0.3])
confidence_T = confidence.reshape(5, 1)
print(confidence_T)
print(confidence_T.shape)


single_command_output = np.array([[[0.1, 0.7, 0.2]]])
new_single_command_output = single_command_output.squeeze()
print(new_single_command_output.shape)

[[0.9 ]
 [0.4 ]
 [0.7 ]
 [0.95]
 [0.3 ]]
(5, 1)
(3,)


# Question 6

In [6]:
# 6
import numpy as np

power_readings = np.array([2.1, -0.5, 3.4, -1.1, 0, 5.6])

power_new = np.clip(power_readings, 0, None)
power_new1 = np.where(power_readings < 0, 0, power_readings)

matrix = np.array([[-0.4, 1.2, 0.0], [2.1, -1.5, 0.3]])
relu_output = np.maximum(0, matrix)
relu_output1 = np.where(matrix < 0, 0, matrix)
print(relu_output1)

[[0.  1.2 0. ]
 [2.1 0.  0.3]]


# Question 7

In [8]:
# Q7
import numpy as np

logits = np.array([[2.5, 0.3, 0.1], [0.2, 0.1, 3.5], [1.0, 1.2, 0.9]])


logits_exp = np.exp(logits)
sum_exp_Z = np.sum(logits_exp, axis=1, keepdims=True)
probabilities = logits_exp / sum_exp_Z

print(probabilities)
print("-" * 30)
logits_exp = np.exp(logits)
sum_exp_Z = np.sum(logits_exp, axis=1)
probabilities = logits_exp / sum_exp_Z

print(probabilities)

print("-" * 30)
logits_exp = np.exp(logits)
sum_exp_Z = np.sum(logits_exp, axis=0, keepdims=True)
probabilities = logits_exp / sum_exp_Z

print(probabilities)

[[0.83227834 0.09221907 0.07550259]
 [0.03446199 0.0311825  0.93435551]
 [0.31987306 0.39069383 0.28943311]]
------------------------------
[[0.83227834 0.03808639 0.13005068]
 [0.08344326 0.0311825  3.89685158]
 [0.1857064  0.0936774  0.28943311]]
------------------------------
[[0.75563572 0.23373585 0.03012988]
 [0.07575916 0.19136673 0.90281483]
 [0.16860512 0.57489742 0.06705529]]


# Question 8

In [9]:
# Q8
cart_prices = np.array([120, 45, 300, 15, 80])
discount_items = cart_prices[:2].copy()
print(discount_items)
discount_items[0] = 0
print(cart_prices)

[120  45]
[120  45 300  15  80]
