In [9]:
#1
import numpy as np

scores = [72, 85, 90, 66, 78]
a = np.array(scores)
b = np.size(scores)
c = np.shape(scores)
d = np.ndim(scores)

print(a)
print(b)
print(c)
print(d)


[72 85 90 66 78]
5
(5,)
1


In [10]:
import numpy as np
grades=np.array([[18,15,12,20],[14,17,19,16],[20,20,18,15]])

student2_row = grades[1]
final_exam = grades[:,-1]
sub_matrix = grades[:2,:2]
sub_matrix


array([[18, 15],
       [14, 17]])

In [11]:

a = np.array([3, 6, 9])
b = np.array([1, 2, 3])

sum_arr = a + b
def_arr = a - b
dot_arr = a * b

print("sum_arr", sum_arr)
print("def_arr",def_arr)
print("dot_arr",dot_arr)

sum_arr [ 4  8 12]
def_arr [2 4 6]
dot_arr [ 3 12 27]


In [12]:

# Q4

import numpy as np

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3,3)

print(x)

v = np.array([100, 0, -5])

print(v + x)




[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[101   2  -2]
 [104   5   1]
 [107   8   4]]


In [13]:
# Q5
point_A = np.array([2, 3, 5]) 
point_B = np.array([7, 1, 9]) 

euclidean_distance = np.linalg.norm(point_A - point_B)
print(euclidean_distance)



6.708203932499369


In [14]:
#Q6
import numpy as np
M = np.array([
[80, 70, 90],
[60, 85, 75],
[95, 60, 80],
[70, 70, 70]
])
#print(np.transpose(M))
M2=M.reshape(6,2)
print(M2)

print(M.reshape(2,6))

## reshape(2,6) بنظر منطقی تر می آید چونکه
#  اطلاعات دانش آموزان همچنان قابل تفکیک است


[[80 70]
 [90 60]
 [85 75]
 [95 60]
 [80 70]
 [70 70]]
[[80 70 90 60 85 75]
 [95 60 80 70 70 70]]


In [ ]:
#Q7

import numpy as np
M = np.array([
[80, 70, 90],
[60, 85, 75],
[95, 60, 80],
[70, 70, 70]
])
weights = np.array([0.5, 0.3, 0.2])
prodm=M*weights
print(prodm)
print(np.sum(prodm,axis=1))
print(np.dot(M,weights))


[[40.  21.  18. ]
 [30.  25.5 15. ]
 [47.5 18.  16. ]
 [35.  21.  14. ]]
[79.  70.5 81.5 70. ]
[79.  70.5 81.5 70. ]


In [ ]:
# بخش 2

data = np.array([[32,55,9,7],
                [28,35,8,5],
                [18,50,6,4],
                [30,20,5,3],
                [22,75,7,6],
                [25,40,9,5],
                [20,45,8,4],
                [17,45,4,3]])
# 2B
mean = np.mean(data, axis=0)
print(mean)
max_m = np.max(data, axis=0)
print(max_m)
min_m = np.min(data, axis=0)
print(min_m)
std = np.std(data, axis=0)
print(std)
var = np.var(data,axis=0)
print(var)

scaled_data = ((data - min_m) / (max_m - min_m))
print(scaled_data)
# اسکیلینگ باعث میشود که فاصله ها در یک رنج (0 -1) قرار بگیرند و مقایسه فاصله ها به درستی انجام شود.

# 2c
ideal = np.array([26, 40, 8, 4])
scaled_ideal = ((ideal - min_m) / (max_m - min_m))

euclidean = np.linalg.norm(scaled_data - scaled_ideal,axis= 1)
print(f"euclidean: {euclidean} ")
print(f" min euclidean:{np.min(euclidean)}")
min_index = np.argmin(euclidean)
print(min_index)
print(data[min_index])
print('---' * 30)
max_index = np.argmax(euclidean)
print(max_index)
print(data[max_index])


# cosine_similarity = ((np.dot(scaled_data,scaled_ideal)) / (np.linalg.norm(scaled_data,axis=1) * np.linalg.norm(scaled_ideal)))
norms_data = np.linalg.norm(scaled_data, axis=1) # Shape: (8,)
norm_ideal = np.linalg.norm(scaled_ideal) # Shape: ()

cosine_similarity = np.dot(scaled_data, scaled_ideal) / (norms_data * norm_ideal)
print(f"cosine_similarity: {cosine_similarity}")
print(f"max cosine: {np.argmax(cosine_similarity)}")
print(f"euclidean: {euclidean} ")
print(f"min euclidean: {np.argmin(euclidean)} ")

print("--" * 30)

# 2D
weights = np.array([0.1, 0.2, 0.3, 0.4])

scaled_data_weighted = scaled_data * weights
# print(f"scaled_data_weighted:\n{scaled_data_weighted}")

scaled_ideal_weighted = scaled_ideal * weights
# print(f'scaled_ideal before weighted:\n{scaled_ideal}')
# print(f'scaled_ideal_weighted:\n{scaled_ideal_weighted}')

cosine_similarity_weighted = ((np.dot(scaled_data_weighted,scaled_ideal_weighted)) / (np.linalg.norm(scaled_data_weighted,axis=1) * np.linalg.norm(scaled_ideal_weighted)))
print(f"cosine_similarity_weighted:\n {cosine_similarity_weighted}")

[24.    45.625  7.     4.625]
[32 75  9  7]
[17 20  4  3]
[ 5.26782688 14.88235112  1.73205081  1.31695672]
[ 27.75     221.484375   3.         1.734375]
[[1.         0.63636364 1.         1.        ]
 [0.73333333 0.27272727 0.8        0.5       ]
 [0.06666667 0.54545455 0.4        0.25      ]
 [0.86666667 0.         0.2        0.        ]
 [0.33333333 1.         0.6        0.75      ]
 [0.53333333 0.36363636 1.         0.5       ]
 [0.2        0.45454545 0.8        0.25      ]
 [0.         0.45454545 0.         0.        ]]
euclidean: [0.91481155 0.29756048 0.69101541 0.79110209 0.87525413 0.32702361
 0.41020052 1.03477749] 
 min euclidean:0.2975604822346125
1
[28 35  8  5]
------------------------------------------------------------------------------------------
7
[17 45  4  3]
cosine_similarity: [0.51713352 0.35847246 0.17064952 0.18690861 0.33839704 0.37855355
 0.27150929 0.04543233]
max cosine: 0
euclidean: [0.91481155 0.29756048 0.69101541 0.79110209 0.87525413 0.32702361
 0.4102