# Question 1

In [1]:
##Q1 and Q2
import numpy as np

customers = np.array(
    [
        [22, 2, 15, 1],
        [25, 4, 20, 2],
        [47, 10, 120, 12],
        [52, 12, 150, 15],
        [35, 6, 60, 6],
        [38, 7, 70, 7],
        [19, 1, 10, 1],
        [60, 8, 130, 10],
        [41, 9, 90, 9],
        [28, 5, 35, 4],
        [33, 6, 55, 5],
        [55, 11, 160, 14],
    ]
)

x = customers

x_min = np.min(x, axis=0)
x_max = np.max(x, axis=0)
x_mean = np.mean(x, axis=0)
x_std = np.std(x, axis=0)
print(x_min)
print(x_max)
print(x_mean)
print(x_std)
hightest_mean = np.argmax(x_mean)
print(hightest_mean)
hightest_mstd = np.argmax(x_std)
print(hightest_mstd)

[19  1 10  1]
[ 60  12 160  15]
[37.91666667  6.75       76.25        7.16666667]
[12.84171804  3.29456623 50.99530207  4.66964191]
2
2


# Question 3

In [ ]:
# scaling dataset

X_scaled = (x - x_min) / (x_max - x_min)
print(f"scaled dataset:\n{X_scaled}")
x_scaled_mean = np.mean(X_scaled, axis=0)
print(f"mean before scaling:\n{x_mean}\nscaled dataset features mean:\n{x_scaled_mean}")

scaled dataset:
[[0.07317073 0.09090909 0.03333333 0.        ]
 [0.14634146 0.27272727 0.06666667 0.07142857]
 [0.68292683 0.81818182 0.73333333 0.78571429]
 [0.80487805 1.         0.93333333 1.        ]
 [0.3902439  0.45454545 0.33333333 0.35714286]
 [0.46341463 0.54545455 0.4        0.42857143]
 [0.         0.         0.         0.        ]
 [1.         0.63636364 0.8        0.64285714]
 [0.53658537 0.72727273 0.53333333 0.57142857]
 [0.2195122  0.36363636 0.16666667 0.21428571]
 [0.34146341 0.45454545 0.3        0.28571429]
 [0.87804878 0.90909091 1.         0.92857143]]
mean before scaling:
[37.91666667  6.75       76.25        7.16666667]
scaled dataset features mean:
[0.46138211 0.52272727 0.44166667 0.44047619]


# Question 4

In [ ]:
# variables
ref_points = np.array(
    [
        # low activity
        [23, 2, 15, 1],
        # normal
        [32, 5, 45, 4],
        # loyal
        [42, 8, 85, 8],
        # VIP
        [55, 12, 150, 14],
    ]
)
# scaling new dataset
ref_points_scaled = (ref_points - x_min) / (x_max - x_min)
print(f"scaled new dataset:\n{ref_points_scaled}")
ref_names = np.array(["low activity", "normal", "loyal", "VIP"])

# distance
distances = np.linalg.norm(
    ref_points_scaled[:, np.newaxis, :] - X_scaled[np.newaxis, :, :], axis=2
).T
nearest_idx = distances.argmin(axis=1)

# mapping to labels
mapping = {0: "low activity", 1: "normal", 2: "loyal", 3: "VIP"}
predicted_labels = np.vectorize(mapping.get)(nearest_idx)
print(predicted_labels)
for i, (customer, label) in enumerate(zip(customers, predicted_labels), start=1):
    print(f"{i}. Customer {customer}\nwith label = {label}\n{"--"*10}")

scaled new dataset:
[[0.09756098 0.09090909 0.03333333 0.        ]
 [0.31707317 0.36363636 0.23333333 0.21428571]
 [0.56097561 0.63636364 0.5        0.5       ]
 [0.87804878 1.         0.93333333 0.92857143]]
['low activity' 'low activity' 'VIP' 'VIP' 'normal' 'loyal' 'low activity'
 'VIP' 'loyal' 'normal' 'normal' 'VIP']
1. Customer [22  2 15  1]
with label = low activity
--------------------
2. Customer [25  4 20  2]
with label = low activity
--------------------
3. Customer [ 47  10 120  12]
with label = VIP
--------------------
4. Customer [ 52  12 150  15]
with label = VIP
--------------------
5. Customer [35  6 60  6]
with label = normal
--------------------
6. Customer [38  7 70  7]
with label = loyal
--------------------
7. Customer [19  1 10  1]
with label = low activity
--------------------
8. Customer [ 60   8 130  10]
with label = VIP
--------------------
9. Customer [41  9 90  9]
with label = loyal
--------------------
10. Customer [28  5 35  4]
with label = normal
-------

به علت اینکه در حال استفاده از شباهت برای دسته بندی هستیم و مدل بر اساس لیبل آموزش نمیبینه 

# 4 Updated

In [28]:
# Q4
# variables
ref_points = np.array(
    [
        # low activity
        [23, 2, 15, 1],
        # normal
        [32, 5, 45, 4],
        # loyal
        [42, 8, 85, 8],
        # VIP
        [55, 12, 150, 14],
    ]
)
# scaling new dataset
ref_points_scaled = (ref_points - x_min) / (x_max - x_min)
print(f"scaled new dataset:\n{ref_points_scaled}")
ref_names = np.array(["low activity", "normal", "loyal", "VIP"])

# distance
distances = np.linalg.norm(
    ref_points_scaled[:, np.newaxis, :] - X_scaled[np.newaxis, :, :], axis=2
).T
nearest_idx = distances.argmin(axis=1)

# mapping to labels
mapping = {0: "low activity", 1: "normal", 2: "loyal", 3: "VIP"}
predicted_labels = np.vectorize(mapping.get)(nearest_idx)
print(predicted_labels)
low = []
normal = []
loyal = []
vip = []
for i, (customer, label) in enumerate(zip(customers, predicted_labels), start=1):
    if label == "low activity":
        low.append(customer)
    elif label == "normal":
        normal.append(customer)
    elif label == "loyal":
        loyal.append(customer)
    else:
        vip.append(customer)
        print(f"{i}. Customer {customer}\nwith label = {label}\n{"--"*10}")

scaled new dataset:
[[0.09756098 0.09090909 0.03333333 0.        ]
 [0.31707317 0.36363636 0.23333333 0.21428571]
 [0.56097561 0.63636364 0.5        0.5       ]
 [0.87804878 1.         0.93333333 0.92857143]]
['low activity' 'low activity' 'VIP' 'VIP' 'normal' 'loyal' 'low activity'
 'VIP' 'loyal' 'normal' 'normal' 'VIP']
3. Customer [ 47  10 120  12]
with label = VIP
--------------------
4. Customer [ 52  12 150  15]
with label = VIP
--------------------
8. Customer [ 60   8 130  10]
with label = VIP
--------------------
12. Customer [ 55  11 160  14]
with label = VIP
--------------------


# Question 5

In [29]:
# Q5

print(f"low: {len(low)}")
print(f"normal: {len(normal)}")
print(f"loyal: {len(loyal)}")
print(f"vip: {len(vip)}")

means = np.mean(customers, axis=1)
print(means)
feature_names = np.array(
    ["age", "monthly_visits", "avg_order_value", "total_purchases"]
)

for i, (mean, name) in enumerate(zip(means, feature_names), start=1):
    print(f"{i}.: {name} ::with mean = {mean:>20}")

argmax_avg = np.argmax(customers[:, 2])
print(f"max_avg: {predicted_labels[argmax_avg]}")

argmax_month = np.argmax(customers[:, 1])
print(f"argmax_month: {predicted_labels[argmax_month]}")

low: 3
normal: 3
loyal: 2
vip: 4
[10.   12.75 47.25 57.25 26.75 30.5   7.75 52.   37.25 18.   24.75 60.  ]
1.: age ::with mean =                 10.0
2.: monthly_visits ::with mean =                12.75
3.: avg_order_value ::with mean =                47.25
4.: total_purchases ::with mean =                57.25
max_avg: VIP
argmax_month: VIP


# Question 6

In [30]:
# Q6


total_purchases = customers[:, 3]
# total_purchases_labeled=map(lambda x:"valuable" if x >=8 else "regular",total_purchases)
total_purchases_labeled = np.where(total_purchases >= 8, "valuable", "regular")
print(f"total_purchases_labeled=\n{total_purchases_labeled}")
sum_valueble = np.sum(total_purchases_labeled == "valuable")
sum_regular = len(total_purchases_labeled) - sum_valueble
print(f"sum valueble={sum_valueble}\nsum regular={sum_regular}")
average_oav_v = np.mean(customers[total_purchases_labeled == "valuable", 2])
print(f"average_oav_v={average_oav_v}")
average_oav_r = np.mean(customers[total_purchases_labeled == "regular", 2])
print(f"average_oav_r={average_oav_r:.2f}")

average_monthly_v_v = np.mean(customers[total_purchases_labeled == "valuable", 1])
print(f"average_monthly_v_v={average_monthly_v_v}")
average_monthly_v_r = np.mean(customers[total_purchases_labeled == "regular", 1])
print(f"average_monthly_v_r={average_monthly_v_r:.2f}")
# به کمک rule
# classification

total_purchases_labeled=
['regular' 'regular' 'valuable' 'valuable' 'regular' 'regular' 'regular'
 'valuable' 'valuable' 'regular' 'regular' 'valuable']
sum valueble=5
sum regular=7
average_oav_v=130.0
average_oav_r=37.86
average_monthly_v_v=10.0
average_monthly_v_r=4.43


# Question 7

In [31]:
# Q7
customers = np.array(
    [
        [22, 2, 15, 1],
        [25, 4, 20, 2],
        [47, 10, 120, 12],
        [52, 12, 150, 15],
        [35, 6, 60, 6],
        [38, 7, 70, 7],
        [19, 1, 10, 1],
        [60, 8, 130, 10],
        [41, 9, 90, 9],
        [28, 5, 35, 4],
        [33, 6, 55, 5],
        [55, 11, 160, 14],
    ]
)

outlier_customer = np.array([[30, 1, 500, 1]])

customers_with_outlier = np.concatenate((customers, outlier_customer))

print(f"customers_with_outlier:\n{customers_with_outlier}")
print(f"customers_with_outlier shape is ==> {customers_with_outlier.shape}")


customers_with_outlier_min = np.min(customers_with_outlier, axis=0)
customers_with_outlier_max = np.max(customers_with_outlier, axis=0)

customers_with_outlier_scaled = (
    customers_with_outlier - customers_with_outlier_min
) / (customers_with_outlier_max - customers_with_outlier_min)

print(f"customers_with_outlier_scaled:\n{customers_with_outlier_scaled}")

center = np.mean(customers_with_outlier_scaled, axis=0)
print(f"center:{center}")

distance = np.linalg.norm(customers_with_outlier_scaled - center, axis=1)
print(f"distance:\n{distance}")

highest_distance = np.argmax(distance)
print(f"highest_distance: {highest_distance}")  # 12 ==> outlier

# 1 ==> outlier : داده پرت
# 2 ==>  مقدار avg_order_value بسیار بزرگی دارد، اما تعداد خرید او کم است
# 3 ==> خیر برچسب نداشتیم
# 4 ==> Unsupervised Learning

customers_with_outlier:
[[ 22   2  15   1]
 [ 25   4  20   2]
 [ 47  10 120  12]
 [ 52  12 150  15]
 [ 35   6  60   6]
 [ 38   7  70   7]
 [ 19   1  10   1]
 [ 60   8 130  10]
 [ 41   9  90   9]
 [ 28   5  35   4]
 [ 33   6  55   5]
 [ 55  11 160  14]
 [ 30   1 500   1]]
customers_with_outlier shape is ==> (13, 4)
customers_with_outlier_scaled:
[[0.07317073 0.09090909 0.01020408 0.        ]
 [0.14634146 0.27272727 0.02040816 0.07142857]
 [0.68292683 0.81818182 0.2244898  0.78571429]
 [0.80487805 1.         0.28571429 1.        ]
 [0.3902439  0.45454545 0.10204082 0.35714286]
 [0.46341463 0.54545455 0.12244898 0.42857143]
 [0.         0.         0.         0.        ]
 [1.         0.63636364 0.24489796 0.64285714]
 [0.53658537 0.72727273 0.16326531 0.57142857]
 [0.2195122  0.36363636 0.05102041 0.21428571]
 [0.34146341 0.45454545 0.09183673 0.28571429]
 [0.87804878 0.90909091 0.30612245 0.92857143]
 [0.26829268 0.         1.         0.        ]]
center:[0.44652908 0.48251748 0.20172684 