# Qustion 1

In [14]:
"""
rows: Every row represents a student.

columns: Every column represents a student's feature.
     First column: study_hours
     Second column: attendance_percent
     Third column: previous_score
     Forth column: final_score

X:

"""

import numpy as np

students = np.array(
    [
        [2, 60, 45, 50],
        [5, 80, 70, 75],
        [1, 40, 35, 38],
        [8, 90, 88, 92],
        [4, 75, 60, 65],
        [7, 85, 80, 84],
        [3, 55, 50, 52],
        [6, 70, 72, 78],
    ]
)

print(f"dtype: {students.dtype}")
print(f"size: {students.size}")
print(f"shape: {students.shape}")
print(f"ndim: {students.ndim}")

X = students[:, :3]
print(f"X:\n{X}")

y = students[:, -1]
print(f"y:\n{y}")

print(f"X.shape:\n{X.shape}")

print(f"y.shape:\n{y.shape}")

dtype: int64
size: 32
shape: (8, 4)
ndim: 2
X:
[[ 2 60 45]
 [ 5 80 70]
 [ 1 40 35]
 [ 8 90 88]
 [ 4 75 60]
 [ 7 85 80]
 [ 3 55 50]
 [ 6 70 72]]
y:
[50 75 38 92 65 84 52 78]
X.shape:
(8, 3)
y.shape:
(8,)


# Question 2

In [15]:
rule_based_label = np.where(y > 60, "pass", "fail")
mask = rule_based_label == "pass"
passed = np.sum(mask)
failed = len(rule_based_label) - passed

print(f"{passed} Student passed\n{failed} Student failed")

5 Student passed
3 Student failed


به این علت که یک شرط توسط یک خبره در حال تعیین لیبل هست و هیچ الگوریتم یادگیری روی داده ها فیت نشده و پیش بینی نکرده این سیستم یک سیستم خبره است 

# Question 3

In [16]:
## Q3

# study_hours, attendance_percent, previous_score
mean_study_hours = np.mean(X[:, 0])
print(f"mean_study_hours: {mean_study_hours}")

min_attendance_percent = np.min(X[:, 1])
print(f"min_attendance_percent: {min_attendance_percent}")

max_attendance_percent = np.max(X[:, 1])
print(f"max_attendance_percent: {max_attendance_percent}")

study_hours = X[:, 0]
attendance_percent = X[:, 1]
effort_score = study_hours * attendance_percent / 100
print(f"effort_score: {effort_score}")
print(f"effort_score: {effort_score.shape}")
print(f"X:\n{X.shape}")
effort_score_new = effort_score.reshape(-1, 1)
print(f"effort_score:\n{effort_score_new.shape}")

# X_new = np.concatenate((X, effort_score_new), axis=1)
X_new_stack = np.hstack((X, effort_score_new))
print(f"X_new shape: {X_new_stack.shape}")

mean_study_hours: 4.5
min_attendance_percent: 40
max_attendance_percent: 90
effort_score: [1.2  4.   0.4  7.2  3.   5.95 1.65 4.2 ]
effort_score: (8,)
X:
(8, 3)
effort_score:
(8, 1)
X_new shape: (8, 4)


# Question 4

In [17]:
## Q4
import numpy as np

students = np.array(
    [
        [2, 60, 45, 50],
        [5, 80, 70, 75],
        [1, 40, 35, 38],
        [8, 90, 88, 92],
        [4, 75, 60, 65],
        [7, 85, 80, 84],
        [3, 55, 50, 52],
        [6, 70, 72, 78],
    ]
)
final_score = students[:, -1]
class_label = np.where(final_score >= 60, "pass", "fail")
print(class_label)
mask = class_label == "pass"
passed = np.sum(mask)
failed = len(class_label) - passed
print(f"passed: {passed}")
print(f"failed: {failed}")

pass_percent = passed / len(class_label) * 100
print(pass_percent)

['fail' 'pass' 'fail' 'pass' 'pass' 'pass' 'fail' 'pass']
passed: 5
failed: 3
62.5


# Question 5

In [18]:
# Q5:
print(f"final_score:{final_score}")
level_label = np.where(
    final_score < 60,
    "weak",
    np.where((60 <= final_score) & (final_score < 80), "normal", "strong"),
)

print(level_label)

weak = np.sum(level_label == "weak")
normal = np.sum(level_label == "normal")
strong = np.sum(level_label == "strong")
print(weak)

weak_sample = students[level_label == "weak"]
print(weak_sample)
mean_study_hours_weak = np.mean(weak_sample[:, 0])
print(f"mean_study_hours_weak: {mean_study_hours_weak}")


normal_sample = students[level_label == "normal"]
print(normal_sample)
mean_study_hours_normal = np.mean(normal_sample[:, 0])
print(f"mean_study_hours_normal: {mean_study_hours_normal}")


strong_sample = students[level_label == "strong"]
print(strong_sample)
mean_study_hours_strong = np.mean(strong_sample[:, 0])
print(f"mean_study_hours_strong: {mean_study_hours_strong}")


# 3 کلاسه هست ==> multiclass classification

final_score:[50 75 38 92 65 84 52 78]
['weak' 'normal' 'weak' 'strong' 'normal' 'strong' 'weak' 'normal']
3
[[ 2 60 45 50]
 [ 1 40 35 38]
 [ 3 55 50 52]]
mean_study_hours_weak: 2.0
[[ 5 80 70 75]
 [ 4 75 60 65]
 [ 6 70 72 78]]
mean_study_hours_normal: 5.0
[[ 8 90 88 92]
 [ 7 85 80 84]]
mean_study_hours_strong: 7.5


# Question 6

In [19]:
# Q6
x = students

x_min = np.min(x, axis=0)
x_max = np.max(x, axis=0)
x_mean = np.mean(x, axis=0)
x_std = np.std(x, axis=0)

x_scaled = (x - x_min) / (x_max - x_min)
print(x_scaled)
print(np.min(x_scaled))
print(np.max(x_scaled))

[[0.14285714 0.4        0.18867925 0.22222222]
 [0.57142857 0.8        0.66037736 0.68518519]
 [0.         0.         0.         0.        ]
 [1.         1.         1.         1.        ]
 [0.42857143 0.7        0.47169811 0.5       ]
 [0.85714286 0.9        0.8490566  0.85185185]
 [0.28571429 0.3        0.28301887 0.25925926]
 [0.71428571 0.6        0.69811321 0.74074074]]
0.0
1.0


# Question 7

In [20]:
# Q7
import numpy as np

students = np.array(
    [
        [2, 60, 45, 50],
        [5, 80, 70, 75],
        [1, 40, 35, 38],
        [8, 90, 88, 92],
        [4, 75, 60, 65],
        [7, 85, 80, 84],
        [3, 55, 50, 52],
        [6, 70, 72, 78],
    ]
)

x = students[:, :3]

x_min = np.min(x, axis=0)
x_max = np.max(x, axis=0)

new_student = np.array([5, 75, 68])

new_student_scaled = (new_student - x_min) / (x_max - x_min)
print(new_student_scaled)

x_scaled = (x - x_min) / (x_max - x_min)

distance = np.sqrt(np.sum((new_student_scaled - x_scaled) ** 2, axis=1))
# distance = np.linalg.norm(new_student_scaled - x_scaled, axis=1)
print(f"distance:\n{distance}")

print(f"Nearest student: {students[np.argmin(distance)]}")

final_score = students[:, -1]
level_label = np.where(
    final_score < 60, "weak", np.where(final_score < 80, "normal", "strong")
)

print(f"Nearest class label:\n{level_label[np.argmin(distance)]}")

[0.57142857 0.7        0.62264151]
distance:
[0.6797034  0.10688309 1.09736642 0.64503713 0.20782702 0.41580819
 0.59747485 0.1900109 ]
Nearest student: [ 5 80 70 75]
Nearest class label:
normal


# Question 8

In [21]:
# import
import numpy as np

# variables
new_students = np.array([[2, 50, 40], [6, 82, 78], [4, 65, 58], [8, 88, 85]])
students = np.array(
    [
        [2, 60, 45, 50],
        [5, 80, 70, 75],
        [1, 40, 35, 38],
        [8, 90, 88, 92],
        [4, 75, 60, 65],
        [7, 85, 80, 84],
        [3, 55, 50, 52],
        [6, 70, 72, 78],
    ]
)

x = students[:, :3]

x_min = np.min(x, axis=0)
x_max = np.max(x, axis=0)
x_scaled = (x - x_min) / (x_max - x_min)
new_student_scaled = (new_students - x_min) / (x_max - x_min)

level_label = np.where(
    final_score < 60, "weak", np.where(final_score < 80, "normal", "strong")
)
print(f"shape x:{x_scaled.shape}")
print(f"shape new samples: {new_student_scaled.shape}")
# 4.1.3  1.8.3
distance = np.linalg.norm(
    x_scaled[np.newaxis, :, :] - new_student_scaled[:, np.newaxis, :], axis=2
)
nearest_neighbor = distance.argmin(axis=1)
print(f"distances: \n{distance}")
print(f"nearest neighbor:\n{nearest_neighbor}")
labels = level_label[nearest_neighbor]
for i, label in enumerate(labels, start=1):
    print(f"student {i}, label = {label}")
distance.shape

shape x:(8, 3)
shape new samples: (4, 3)
distances: 
[[0.22113336 0.92955483 0.26326437 1.48152442 0.68849988 1.25291732
  0.25692026 0.92253626]
 [0.95279224 0.21164138 1.3689578  0.37793189 0.46537747 0.15947463
  0.86854842 0.26536004]
 [0.38961059 0.40208452 0.78866768 0.94706353 0.20352885 0.71831524
  0.28843036 0.40175661]
 [1.27196368 0.53793415 1.67678157 0.0693108  0.78525774 0.18140597
  1.17554342 0.52095721]]
nearest neighbor:
[0 5 4 3]
student 1, label = weak
student 2, label = strong
student 3, label = normal
student 4, label = strong


(4, 8)

# Question 9

In [22]:
# Q9

mapping = {"weak": "fail", "normal": "pass", "strong": "pass"}
predicted_labels = level_label[nearest_neighbor]
predicted_labels = np.vectorize(mapping.get)(predicted_labels)
print(predicted_labels)

true_labels = np.array(["fail", "pass", "pass", "pass"])

print(f"true_labels:{true_labels.shape}")
print(f"predicted_labels:{predicted_labels.shape}")

correct_predictions = true_labels == predicted_labels
print(f"correct_predictions:{correct_predictions}")

number_of_correct_predictions = np.sum(correct_predictions)
print(f"number_of_correct_predictions:{number_of_correct_predictions}")

accuracy = (number_of_correct_predictions / len(predicted_labels)) * 100

print(f"accuracy:{accuracy}")

# Accuracy ==> دقت
# Accuracy = 0.75 ==> از هر 4 پیش بینی 3 تا درست بوده است.

['fail' 'pass' 'pass' 'pass']
true_labels:(4,)
predicted_labels:(4,)
correct_predictions:[ True  True  True  True]
number_of_correct_predictions:4
accuracy:100.0


# Question 10 

In [23]:
"""This question will tell us somthing about regression"""

# imports
import numpy as np

# variables
actual_scores = np.array([50, 75, 38, 92, 65])
predicted_scores = np.array([55, 70, 45, 88, 60])
# regression error
error = predicted_scores - actual_scores
# error output
print(f"error of prediction vs actual values:\n{error}")
# absolute error
abs_error = np.abs(predicted_scores - actual_scores)
print(f"absolute error of prediction vs actual values:\n{abs_error}")

# MAE metric
mae_result = np.mean(abs_error)
# output
print(f"MAE metric:\n{mae_result}")

error of prediction vs actual values:
[ 5 -5  7 -4 -5]
absolute error of prediction vs actual values:
[5 5 7 4 5]
MAE metric:
5.2


این بخش مربوط به رگرسیون است به این علت که در حال محاسبه فاصله نقاط پیش بینی شده برای مقادیر پیوسته با مقادیر پیوسته حقیقی هستیم 

ارور خالی نمی تواند یک عدد برای ارزیابی عملکرد مدل بدهد پس از یک معیار محاسبه میانگین خطا استفاده میکنیم تا عملکرد مدل برای تمام سمپل ها رو به نمایندگی یک عدد ببینیم 

قدر مطلق خطا رو میانگین میگیریم تا اعداد منفی در متغییر ارور باعث به هم ریختن مقادیر خطا سمپل ها نشه و همه اعداد مثبت بشه 


# Question 11

In [24]:
# imports
import numpy as np

# variables
# features: study_hours,
attendanceX1 = np.array([[2, 60], [5, 80], [1, 40], [8, 90]])
# label: pass/fail
y1 = np.array(["fail", "pass", "fail", "pass"])

# what kind of ML ?
print(f"This labels are in Supervised category:\n{y1}")
# customer features without labels
X2 = np.array([[22, 2, 15], [25, 4, 20], [52, 12, 150], [55, 11, 160]])
print(f"This samples are in Unsupervised category becaues does not have label:\n{X2}")

# some samples have labels, some do not
X3 = np.array([[2, 60], [5, 80], [1, 40], [8, 90]])
y3 = np.array(["fail", "pass", "unknown", "unknown"])
print(f"This labels are in seme supervised:\n{y3}")

# agent takes actions and receives rewards
actions = np.array(["left", "right", "jump", "right"])
rewards = np.array([-1, 2, 5, 3])
print(f"This is reinforcement:\nactions{actions}\nrewards{rewards}")

This labels are in Supervised category:
['fail' 'pass' 'fail' 'pass']
This samples are in Unsupervised category becaues does not have label:
[[ 22   2  15]
 [ 25   4  20]
 [ 52  12 150]
 [ 55  11 160]]
This labels are in seme supervised:
['fail' 'pass' 'unknown' 'unknown']
This is reinforcement:
actions['left' 'right' 'jump' 'right']
rewards[-1  2  5  3]


# Question 12

In [ ]:
# imports
import numpy as np

# If final_score >= 60, predict pass
np.where(final_score >= 60, "pass", "fail")
# به این علت که در این روش در حال پیاده سازی یک قانون ساخته شده به دست انسان هستیم برای کلاس بندی نمونه ها
# در ماشین لرنینگ فرد قانون را نمی نویسد بلکه مدل بر اساس الگو های موجود در داده ها یادمیگیره چه قانونی بزاره
# یادگیری عمییق زمانی استفاده میشود که با مسائل پیچیده مانند تشخیص گفتار انسان و تشخیص چهره طرف هستیم و
#  حچم داده عظیمی داریم و سخت افزار کافی برای پیاده سازی شبکه های عصبی چند لایه داریم

array(['fail', 'pass', 'fail', 'pass', 'pass', 'pass', 'fail', 'pass'],
      dtype='<U4')

# Question 13 answers


In [26]:
# Dataset: مجموعه‌ کل داده‌هایی است که برای آموزش، اعتبارسنجی یا تست مدل استفاده می‌شود.
# Sample: یک ردیف یا یک نمونه‌ مستقل از داده‌هاست که معمولاً شامل چند ویژگی است.
# Feature: هر ورودی یا مشخصه‌ای از داده است که مدل از آن برای یادگیری استفاده می‌کند.
# Label: خروجی درست یا پاسخ هدفی است که مدل باید آن را پیش‌بینی کند.
# Regression vs Classification: در Regression خروجی عددی پیوسته است، اما در Classification خروجی یک کلاس یا دسته است.
# Feature Scaling: مهم است چون باعث می‌شود ویژگی‌ها با مقیاس‌های خیلی متفاوت روی یادگیری مدل اثر نامتوازن نگذارند.
# Distance در ML: در روش‌هایی مثل KNN و K-means معیار شباهت/تفاوت نمونه‌هاست، پس مستقیماً روی نتیجه اثر می‌گذارد.
# Accuracy: معمولاً برای مسائل Classification استفاده می‌شود تا درصد پیش‌بینی‌های درست را نشان دهد.
# Absolute Error: معمولاً برای مسائل Regression استفاده می‌شود تا مقدار خطای عددی پیش‌بینی را اندازه بگیرد.
# Rule-based AI vs ML: در Rule-based قوانین را انسان می‌نویسد، اما در ML سیستم الگوها را از داده یاد می‌گیرد.
# ML vs Deep Learning: Deep Learning زیرمجموعه‌ای از ML است که با شبکه‌های عصبی عمیق روی داده‌های پیچیده بهتر کار می‌کند.
# هدف اصلی ML: هدف اصلی مدل یاد گرفتن الگوها برای پیش‌بینی بهتر روی داده‌های جدید است، نه حفظ کردن داده‌ها.