# Question 1

In [40]:
# imports
import numpy as np

# variables
customers = np.array(
    [
        [22, 2, 15, 1],
        [25, 4, 20, 2],
        [47, 10, 120, 12],
        [52, 12, 150, 15],
        [35, 6, 60, 6],
        [38, 7, 70, 7],
        [19, 1, 10, 1],
        [60, 8, 130, 10],
        [41, 9, 90, 9],
        [28, 5, 35, 4],
        [33, 6, 55, 5],
        [55, 11, 160, 14],
    ]
)
# results
print(
    "ndim ",
    customers.ndim,
    "shape",
    customers.shape,
    "size",
    customers.size,
    "dtype",
    customers.dtype,
    "\n",
    sep="\n",
)

ndim 
2
shape
(12, 4)
size
48
dtype
int64




# Question 2

In [41]:
# imports
import numpy as np

# variables
x = customers
# statistics
x_min = np.min(x, axis=0)
x_max = np.max(x, axis=0)
x_mean = np.mean(x, axis=0)
x_std = np.std(x, axis=0)
# outputs
print(f"min :{x_min}")
print(f"max: {x_max}")
print(f"mean: {x_mean}")
print(f"std: {x_std}")

# the features with most mean and std
highest_mean = np.argmax(x_mean)
print(f"highest mean:\n{highest_mean}")
highest_std = np.argmax(x_std)
print(f"highest std:\n{highest_std}")

min :[19  1 10  1]
max: [ 60  12 160  15]
mean: [37.91666667  6.75       76.25        7.16666667]
std: [12.84171804  3.29456623 50.99530207  4.66964191]
highest mean:
2
highest std:
2


# Question 3

In [42]:
# scaling dataset
# Min Max scaling
X_scaled = (x - x_min) / (x_max - x_min)
# outputs
print(f"scaled dataset:\n{X_scaled}")
x_scaled_mean = np.mean(X_scaled, axis=0)
print(
    f"means before scaling:\n{x_mean}\nscaled dataset features mean:\n{x_scaled_mean}"
)

scaled dataset:
[[0.07317073 0.09090909 0.03333333 0.        ]
 [0.14634146 0.27272727 0.06666667 0.07142857]
 [0.68292683 0.81818182 0.73333333 0.78571429]
 [0.80487805 1.         0.93333333 1.        ]
 [0.3902439  0.45454545 0.33333333 0.35714286]
 [0.46341463 0.54545455 0.4        0.42857143]
 [0.         0.         0.         0.        ]
 [1.         0.63636364 0.8        0.64285714]
 [0.53658537 0.72727273 0.53333333 0.57142857]
 [0.2195122  0.36363636 0.16666667 0.21428571]
 [0.34146341 0.45454545 0.3        0.28571429]
 [0.87804878 0.90909091 1.         0.92857143]]
means before scaling:
[37.91666667  6.75       76.25        7.16666667]
scaled dataset features mean:
[0.46138211 0.52272727 0.44166667 0.44047619]


# Question 4

In [43]:
# variables
ref_points = np.array(
    [
        # low activity
        [23, 2, 15, 1],
        # normal
        [32, 5, 45, 4],
        # loyal
        [42, 8, 85, 8],
        # VIP
        [55, 12, 150, 14],
    ]
)
# scaling new dataset
ref_points_scaled = (ref_points - x_min) / (x_max - x_min)
print(f"scaled new dataset:\n{ref_points_scaled}")
ref_names = np.array(["low activity", "normal", "loyal", "VIP"])

# distance
distances = np.linalg.norm(
    ref_points_scaled[:, np.newaxis, :] - X_scaled[np.newaxis, :, :], axis=2
).T
nearest_idx = distances.argmin(axis=1)

# mapping to labels
mapping = {0: "low activity", 1: "normal", 2: "loyal", 3: "VIP"}
predicted_labels = np.vectorize(mapping.get)(nearest_idx)
print(predicted_labels)
for i, (customer, label) in enumerate(zip(customers, predicted_labels), start=1):
    print(f"{i}. Customer {customer}\nwith label = {label}\n{"--"*10}")

scaled new dataset:
[[0.09756098 0.09090909 0.03333333 0.        ]
 [0.31707317 0.36363636 0.23333333 0.21428571]
 [0.56097561 0.63636364 0.5        0.5       ]
 [0.87804878 1.         0.93333333 0.92857143]]
['low activity' 'low activity' 'VIP' 'VIP' 'normal' 'loyal' 'low activity'
 'VIP' 'loyal' 'normal' 'normal' 'VIP']
1. Customer [22  2 15  1]
with label = low activity
--------------------
2. Customer [25  4 20  2]
with label = low activity
--------------------
3. Customer [ 47  10 120  12]
with label = VIP
--------------------
4. Customer [ 52  12 150  15]
with label = VIP
--------------------
5. Customer [35  6 60  6]
with label = normal
--------------------
6. Customer [38  7 70  7]
with label = loyal
--------------------
7. Customer [19  1 10  1]
with label = low activity
--------------------
8. Customer [ 60   8 130  10]
with label = VIP
--------------------
9. Customer [41  9 90  9]
with label = loyal
--------------------
10. Customer [28  5 35  4]
with label = normal
-------

به علت اینکه در حال استفاده از شباهت برای دسته بندی هستیم و مدل بر اساس لیبل آموزش نمیبینه 

# 4 another way

In [44]:
# Q4
# variables
ref_points = np.array(
    [
        # low activity
        [23, 2, 15, 1],
        # normal
        [32, 5, 45, 4],
        # loyal
        [42, 8, 85, 8],
        # VIP
        [55, 12, 150, 14],
    ]
)
# scaling new dataset
ref_points_scaled = (ref_points - x_min) / (x_max - x_min)
print(f"scaled new dataset:\n{ref_points_scaled}")
ref_names = np.array(["low activity", "normal", "loyal", "VIP"])

# distance
distances = np.linalg.norm(
    ref_points_scaled[:, np.newaxis, :] - X_scaled[np.newaxis, :, :], axis=2
).T
# label index
nearest_idx = distances.argmin(axis=1)

# mapping numbers to labels
mapping = {0: "low activity", 1: "normal", 2: "loyal", 3: "VIP"}
predicted_labels = np.vectorize(mapping.get)(nearest_idx)
# check output
print(predicted_labels)
# to slice classes samples
low = []
normal = []
loyal = []
vip = []
# the slicer loop
for i, (customer, label) in enumerate(zip(customers, predicted_labels), start=1):
    if label == "low activity":
        low.append(customer)
    elif label == "normal":
        normal.append(customer)
    elif label == "loyal":
        loyal.append(customer)
    else:
        vip.append(customer)
        print(f"{i}. Customer {customer}\nwith label = {label}\n{"--"*10}")

scaled new dataset:
[[0.09756098 0.09090909 0.03333333 0.        ]
 [0.31707317 0.36363636 0.23333333 0.21428571]
 [0.56097561 0.63636364 0.5        0.5       ]
 [0.87804878 1.         0.93333333 0.92857143]]
['low activity' 'low activity' 'VIP' 'VIP' 'normal' 'loyal' 'low activity'
 'VIP' 'loyal' 'normal' 'normal' 'VIP']
3. Customer [ 47  10 120  12]
with label = VIP
--------------------
4. Customer [ 52  12 150  15]
with label = VIP
--------------------
8. Customer [ 60   8 130  10]
with label = VIP
--------------------
12. Customer [ 55  11 160  14]
with label = VIP
--------------------


# Question 5

In [45]:
# imports
import numpy as np

#  variables
low_mean = np.mean(low, axis=0)
normal_mean = np.mean(normal, axis=0)
loyal_mean = np.mean(loyal, axis=0)
vip_mean = np.mean(vip, axis=0)

print(f"low count: {len(low)}")
print(
    f"mean of age:\n{low_mean[0]:.2f}\nmean of monthly visits:\n{low_mean[1]:.2f}\n\
mean of avg order value:\n{low_mean[2]:.2f}\nmean of total purchases:\n{low_mean[3]:.2f}\n"
)

print(f"normal count: {len(normal)}")
print(
    f"mean of age:\n{normal_mean[0]:.2f}\nmean of monthly visits:\n{normal_mean[1]:.2f}\n\
mean of avg order value:\n{normal_mean[2]:.2f}\nmean of total purchases:\n{normal_mean[3]:.2f}\n"
)

print(f"loyal: {len(loyal)}")
print(
    f"mean of age:\n{loyal_mean[0]:.2f}\nmean of monthly visits:\n{loyal_mean[1]:.2f}\n\
mean of avg order value:\n{loyal_mean[2]:.2f}\nmean of total purchases:\n{loyal_mean[3]:.2f}\n"
)

print(f"vip: {len(vip)}")
print(
    f"mean of age:\n{vip_mean[0]:.2f}\nmean of monthly visits:\n{vip_mean[1]:.2f}\n\
mean of avg order value:\n{vip_mean[2]:.2f}\nmean of total purchases:\n{vip_mean[3]:.2f}\n"
)

# avg_order_value
cluster_avg_order_value = np.array(
    [low_mean[2], normal_mean[2], loyal_mean[2], vip_mean[2]]
)
most_avg_value_idx = cluster_avg_order_value.argmax()
print(
    f"{ref_names[most_avg_value_idx]} cluster has most avg order value = {cluster_avg_order_value.max()}"
)
# monthly visit
cluster_monthly_visit = np.array(
    [low_mean[1], normal_mean[1], loyal_mean[1], vip_mean[1]]
)
most_monthly_visit_idx = cluster_monthly_visit.argmax()
print(
    f"{ref_names[most_monthly_visit_idx]} cluster has most monthly visit = {cluster_monthly_visit.max()}"
)

low count: 3
mean of age:
22.00
mean of monthly visits:
2.33
mean of avg order value:
15.00
mean of total purchases:
1.33

normal count: 3
mean of age:
32.00
mean of monthly visits:
5.67
mean of avg order value:
50.00
mean of total purchases:
5.00

loyal: 2
mean of age:
39.50
mean of monthly visits:
8.00
mean of avg order value:
80.00
mean of total purchases:
8.00

vip: 4
mean of age:
53.50
mean of monthly visits:
10.25
mean of avg order value:
140.00
mean of total purchases:
12.75

VIP cluster has most avg order value = 140.0
VIP cluster has most monthly visit = 10.25


# Question 6

In [46]:
# imports
import numpy as np

# variables

total_purchases = customers[:, 3]
# Threshold
total_purchases_labeled = np.where(total_purchases >= 8, "valuable", "regular")
print(f"total_purchases_labeled=\n{total_purchases_labeled}")
sum_valueble = np.sum(total_purchases_labeled == "valuable")
sum_regular = len(total_purchases_labeled) - sum_valueble
print(f"sum valueble={sum_valueble}\nsum regular={sum_regular}")
average_oav_v = np.mean(customers[total_purchases_labeled == "valuable", 2])
print(f"average_oav_v={average_oav_v}")
average_oav_r = np.mean(customers[total_purchases_labeled == "regular", 2])
print(f"average_oav_r={average_oav_r:.2f}")

average_monthly_v_v = np.mean(customers[total_purchases_labeled == "valuable", 1])
print(f"average_monthly_v_v={average_monthly_v_v}")
average_monthly_v_r = np.mean(customers[total_purchases_labeled == "regular", 1])
print(f"average_monthly_v_r={average_monthly_v_r:.2f}")
# به کمک rule
# classification

total_purchases_labeled=
['regular' 'regular' 'valuable' 'valuable' 'regular' 'regular' 'regular'
 'valuable' 'valuable' 'regular' 'regular' 'valuable']
sum valueble=5
sum regular=7
average_oav_v=130.0
average_oav_r=37.86
average_monthly_v_v=10.0
average_monthly_v_r=4.43


# Question 7

In [47]:
# imports
import numpy as np

# variables
customers = np.array(
    [
        [22, 2, 15, 1],
        [25, 4, 20, 2],
        [47, 10, 120, 12],
        [52, 12, 150, 15],
        [35, 6, 60, 6],
        [38, 7, 70, 7],
        [19, 1, 10, 1],
        [60, 8, 130, 10],
        [41, 9, 90, 9],
        [28, 5, 35, 4],
        [33, 6, 55, 5],
        [55, 11, 160, 14],
    ]
)

outlier_customer = np.array([[30, 1, 500, 1]])

customers_with_outlier = np.concatenate((customers, outlier_customer))

print(f"customers_with_outlier:\n{customers_with_outlier}")
print(f"customers_with_outlier shape is ==> {customers_with_outlier.shape}")


customers_with_outlier_min = np.min(customers_with_outlier, axis=0)
customers_with_outlier_max = np.max(customers_with_outlier, axis=0)

customers_with_outlier_scaled = (
    customers_with_outlier - customers_with_outlier_min
) / (customers_with_outlier_max - customers_with_outlier_min)

print(f"customers_with_outlier_scaled:\n{customers_with_outlier_scaled}")

center = np.mean(customers_with_outlier_scaled, axis=0)
print(f"center:{center}")

distance = np.linalg.norm(customers_with_outlier_scaled - center, axis=1)
print(f"distance:\n{distance}")

highest_distance = np.argmax(distance)
print(f"highest_distance: {highest_distance}")  # 12 ==> outlier

# 1 ==> outlier : داده پرت
# 2 ==>  مقدار avg_order_value بسیار بزرگی دارد، اما تعداد خرید او کم است
# 3 ==> خیر برچسب نداشتیم
# 4 ==> Unsupervised Learning

customers_with_outlier:
[[ 22   2  15   1]
 [ 25   4  20   2]
 [ 47  10 120  12]
 [ 52  12 150  15]
 [ 35   6  60   6]
 [ 38   7  70   7]
 [ 19   1  10   1]
 [ 60   8 130  10]
 [ 41   9  90   9]
 [ 28   5  35   4]
 [ 33   6  55   5]
 [ 55  11 160  14]
 [ 30   1 500   1]]
customers_with_outlier shape is ==> (13, 4)
customers_with_outlier_scaled:
[[0.07317073 0.09090909 0.01020408 0.        ]
 [0.14634146 0.27272727 0.02040816 0.07142857]
 [0.68292683 0.81818182 0.2244898  0.78571429]
 [0.80487805 1.         0.28571429 1.        ]
 [0.3902439  0.45454545 0.10204082 0.35714286]
 [0.46341463 0.54545455 0.12244898 0.42857143]
 [0.         0.         0.         0.        ]
 [1.         0.63636364 0.24489796 0.64285714]
 [0.53658537 0.72727273 0.16326531 0.57142857]
 [0.2195122  0.36363636 0.05102041 0.21428571]
 [0.34146341 0.45454545 0.09183673 0.28571429]
 [0.87804878 0.90909091 0.30612245 0.92857143]
 [0.26829268 0.         1.         0.        ]]
center:[0.44652908 0.48251748 0.20172684 

# Question 8

In [66]:
# imports
import numpy as np

# varialbes
customer_scaled = X_scaled
diff = customer_scaled[:, np.newaxis, :] - customer_scaled[np.newaxis, :, :]
distance = np.linalg.norm(diff, axis=2)
main_diag = np.diag(distance)
# the distance between customer and it self
print(f"diag: \n{main_diag}")
# به این علت که قطر اصلی فاصله مشتری به خود اوست
# fill diag with infitiny
np.fill_diagonal(distance, np.inf)
# nearest customer
nearest_customer = distance.argmin(axis=1)

for i, customer in enumerate(nearest_customer, start=1):
    print(f"customer {i:2} nearest customer is {customer:2}")

diag: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
customer  1 nearest customer is  6
customer  2 nearest customer is  9
customer  3 nearest customer is  8
customer  4 nearest customer is 11
customer  5 nearest customer is 10
customer  6 nearest customer is  4
customer  7 nearest customer is  0
customer  8 nearest customer is  2
customer  9 nearest customer is  5
customer 10 nearest customer is  1
customer 11 nearest customer is  4
customer 12 nearest customer is  3


# Question 9

In [ ]:
# imports
import numpy as np

# variables
new_customer = np.array([40, 9, 100, 9])
new_customer_scaled = (new_customer - x_min) / (x_max - x_min)
distance = np.linalg.norm(new_customer_scaled - ref_points_scaled, axis=1)
nearest_ref_idx = distance.argmin()
# machine learning label
new_customer_class = ref_names[nearest_ref_idx]
print(f"This customer is for {new_customer_class} class.")

# rule base label
# if total_purchases >= 8 => valuable
threshold = np.where(new_customer[3] >= 8, "valuable", "regular")
print(f"Business label is :{threshold}")

This customer is for loyal class.
Business label is :valuable


# Question 10 

In [ ]:
# imports
import numpy as np


# functions
def accuracy(ytrain, ypred):
    """this function return error and accuracy score"""
    corrects = np.sum(ytrain == ypred)
    wrongs = len(ytrain) - corrects
    acc = corrects / len(ytrain)
    error = wrongs / len(ytrain)
    return acc, error


# variables
y_train = np.array(["pass", "fail", "pass", "pass", "fail", "pass"])
y_test = np.array(["pass", "fail", "fail", "pass"])

# model A evaluate
model_A_train_pred = np.array(["pass", "fail", "pass", "pass", "fail", "pass"])
model_A_test_pred = np.array(["fail", "pass", "pass", "fail"])

# model B evaluate
model_B_train_pred = np.array(["pass", "pass", "pass", "pass", "pass", "pass"])
model_B_test_pred = np.array(["pass", "pass", "pass", "pass"])
# model C evaluate
model_C_train_pred = np.array(["pass", "fail", "pass", "fail", "fail", "pass"])
model_C_test_pred = np.array(["pass", "fail", "fail", "pass"])

# measure train acc for A,B,C
a_train_acc = accuracy(y_train, model_A_train_pred)[0]
b_train_acc = accuracy(y_train, model_B_train_pred)[0]
c_train_acc = accuracy(y_train, model_C_train_pred)[0]
# measure test acc for A,B,C
a_test_acc = accuracy(y_test, model_A_test_pred)[0]
b_test_acc = accuracy(y_test, model_B_test_pred)[0]
c_test_acc = accuracy(y_test, model_C_test_pred)[0]

print(f"Model A train accuracy: {a_train_acc:.2f}\n\
Model B train accuracy: {b_train_acc:.2f}\n\
Model C train accuracy: {c_train_acc:.2f}\n")

print(f"Model A test accuracy: {a_test_acc:.2f}\n\
Model B test accuracy: {b_test_acc:.2f}\n\
Model C test accuracy: {c_test_acc:.2f}\n")
# Model A => Best performance on train data
# Model C => Best performance on test data

# if we only check train accuracy there is risk of overfitting ( model loose performance on new datasets )

Model A train accuracy: 1.00
Model B train accuracy: 0.67
Model C train accuracy: 0.83

Model A test accuracy: 0.00
Model B test accuracy: 0.50
Model C test accuracy: 1.00



# Question 11

In [86]:
# Question 11 is only Analytical questions

# Question 12

In [91]:
# imports
import numpy as np


# function
def mae_score(ytrain, ypred):
    """This function measure MAE for regression models"""
    error = ytrain - ypred
    return np.mean(np.abs(error))


# variables
# ground truth
y_train_reg = np.array([50, 75, 38, 92, 65, 84])
y_test_reg = np.array([55, 80, 60, 90])
# models
# Model A
model_A_train_pred = np.array([50, 75, 38, 92, 65, 84])
model_A_test_pred = np.array([30, 100, 40, 120])
# Model B
model_B_train_pred = np.array([60, 60, 60, 60, 60, 60])
model_B_test_pred = np.array([60, 60, 60, 60])
# Model C
model_C_train_pred = np.array([52, 73, 40, 88, 66, 82])
model_C_test_pred = np.array([57, 78, 63, 88])

# MAE train for A,B,C
model_a_mae_train = mae_score(y_train_reg, model_A_train_pred)
model_b_mae_train = mae_score(y_train_reg, model_B_train_pred)
model_c_mae_train = mae_score(y_train_reg, model_C_train_pred)

print(f"Model A train MAE score: {model_a_mae_train:.2f}\n\
Model B train MAE score: {model_b_mae_train:.2f}\n\
Model C train MAE score: {model_c_mae_train:.2f}\n")

# MAE test for A,B,C
model_a_mae_test = mae_score(y_test_reg, model_A_test_pred)
model_b_mae_test = mae_score(y_test_reg, model_B_test_pred)
model_c_mae_test = mae_score(y_test_reg, model_C_test_pred)

print(f"Model A test MAE score: {model_a_mae_test:.2f}\n\
Model B test MAE score: {model_b_mae_test:.2f}\n\
Model C test MAE score: {model_c_mae_test:.2f}\n")

print("Model A overfitted\nModel B underfitted \nModel C good fitted")

Model A train MAE score: 0.00
Model B train MAE score: 18.00
Model C train MAE score: 2.17

Model A test MAE score: 23.75
Model B test MAE score: 13.75
Model C test MAE score: 2.25

Model A overfitted
Model B underfitted 
Model C good fitted


# Question 13

In [ ]:
# imports
import numpy as np


# functions
def mae_score(ytrain, ypred, return_what="mae"):
    """This function measure MAE for regression models"""
    error = ytrain - ypred
    if return_what == "mae":
        return np.mean(np.abs(error))
    return np.abs(error)


# variables
# study_hours, attendance, previous_score
X = np.array(
    [
        [2, 60, 45],
        [5, 80, 70],
        [1, 40, 35],
        [8, 90, 88],
        [4, 75, 60],
        [7, 85, 80],
    ]
)
y = np.array([50, 75, 38, 92, 65, 84])

# simple model
prediction_simple = X[:, 0] * 10

# complex model
prediction_better = 0.4 * X[:, 0] * 10 + 0.3 * X[:, 1] + 0.3 * X[:, 2]

# abs error for each model
# simple
abs_simple = mae_score(y, prediction_simple, "abs")
# complex
abs_complex = mae_score(y, prediction_better, "abs")
# out put
print(f"simple model abs error:\n{abs_simple}\n\
complex model abs error:\n{abs_complex}")
# mae for each model
# simple
mae_simple = mae_score(y, prediction_simple)
# complex
mae_complex = mae_score(y, prediction_better)
# out put
print(f"simple model mae score:\n{mae_simple:.2f}\n\
complex model mae score:\n{mae_complex:.2f}")

# مدل ساده در اینجا به علت سادگی و عدم استفاده از فیچر های کافی پیچیدگی کافی باری حل مسئله رو نداشت
# ولی استفاده بیش از حد از فیچر هم مناسب نیست و ممکنه باعث بیش برازش یا اشباع شدن مدل بشه
# پس در ماشین لرنینگ هیچ چیز دائمی و همیشه مناسبی وجود ندارد و همه چیز به نیاز های مسئله بستگی دارد که در اینجا
# مدل ساده و تک فیچر نتوانست خوب عمل کند

simple model abs error:
[30 25 28 12 25 14]
complex model abs error:
[10.5 10.  11.5  6.6  8.5  6.5]
simple model mae score:
22.33
complex model mae score:
8.93


# Question 14

In [ ]:
# imports
import numpy as np

# variables
models = np.array(["Model A", "Model B", "Model C"])
train_error = np.array([2, 25, 8])
test_error = np.array([40, 30, 10])

# measure gap
gap = train_error - test_error
print(train_error)
print(test_error)
print(gap)
# if train error be small and
#  test error be big the out put will be negative so argmin will help
case_1 = gap.argmin()
print(f"{models[case_1]} is overfitting")
# if we sum test error with gap the bigest out put
#  is the model with big error in train and test because
# if both error be big the output will be small
#  and we can't find out errors are big or small
case_2 = test_error + gap
print(f"{models[case_2.argmax()]} is Underfit model")

# in this case smallest mean gap is good fit
#  because both error are small and the mean will be small too.
case_3 = np.mean([train_error, test_error], axis=0)
print(f"{models[case_3.argmin()]} is good fit ")

# model with smallest test error
case_4 = np.argmin(test_error)
print(f"{models[case_4]} has best Generalization")
# because test datas are unseen datas and if model
# work nice with unseen datas , the model is great.

[ 2 25  8]
[40 30 10]
[-38  -5  -2]
Model A is overfitting
Model B is Underfit model
Model C is good fit 
Model C is  good fit


# Question 15

In [126]:
# Unsupervised Learning: یادگیری بدون برچسب است؛ مدل فقط از روی ساختار خودِ داده الگو پیدا می‌کند.
# Clustering چرا Unsupervised است؟ چون در آن برچسب آماده نداریم و مدل خودش داده‌های مشابه را گروه‌بندی می‌کند.
# cluster label چگونه ساخته شد؟ معمولاً با اجرای الگوریتم خوشه‌بندی، به هر نمونه یک شماره خوشه مثل 0، 1، 2 اختصاص داده می‌شود.
# Outlier: داده‌ای است که به‌طور غیرعادی با بقیه نمونه‌ها خیلی متفاوت است.
# اثر منفی Outlier روی مدل: چون می‌تواند الگوی واقعی داده را منحرف کند و باعث یادگیری اشتباه شود.
# Train/Test Split: برای جدا کردن داده آموزش و ارزیابی است تا ببینیم مدل روی داده جدید چقدر خوب عمل می‌کند.
# Generalization: توانایی مدل برای عملکرد خوب روی داده‌های جدید و ندیده است.
# Overfitting: حالتی که مدل داده آموزشی را خیلی خوب حفظ می‌کند ولی روی داده جدید ضعیف عمل می‌کند.
# Underfitting: حالتی که مدل حتی الگوی اصلی داده آموزشی را هم خوب یاد نگرفته است.
# train بالا و test پایین: مشکل معمولاً Overfitting است.
# train پایین و test پایین: مشکل معمولاً Underfitting است.
# هدف اصلی ML: عملکرد خوب روی داده‌های جدید است، نه فقط خوب بودن روی train data.